title: Introducci√≥n a la Ciencia de Datos
author: Daniel Oropeza and Sebastian Jordan
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/jordanmontt/introduccion-ciencia-de-datos
  path_to_book: docs
  branch: master

html:
  favicon: logo.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true

sphinx:
  config:
    html_show_copyright: false